package gov.cbp.taspd.gtas.model;

import java.util.HashMap;
import java.util.Map;


public enum Carrier {
    MLA("40-Mile Air, Ltd.", "Q5"),
    AIJ("ABC Aerolineas S.A. de C.V.", "4O"),
    TUS("ABSA  -  Aerolinhas Brasileiras S.A.", "M3"),
    AUL("AEROFLOT-NORD", "5N"),
    AHK("AHK Air Hong Kong Limited", "LD"),
    AJV("ANA & JP Express Co. ltd", "9N"),
    CHP("AVIACSA-Consorcio Aviaxsa, S.A. de C.V.", "6A"),
    ADR("Adria Airways - The Airline of Slovenia", "JP"),
    AEE("Aegean Airlines S.A.", "A3"),
    REA("Aer Arann Express", "RE"),
    EIN("Aer Lingus Limited", "EI"),
    NIG("Aero Contractors Nigeria Limited", "AJ"),
    MGE("Aero Micronesia Inc.", ""),
    MNG("Aero Mongolia", "M0"),
    RPB("Aero Republica S.A.", "P5"),
    QCL("Aero V.I.P. Ltda", ""),
    CRN("Aerocaribbean S.A.", "7L"),
    RCF("Aeroflot - Cargo", "SU"),
    AFL("Aeroflot Russian Airlines", "SU"),
    DNV("Aeroflot-Don", "D9"),
    PCP("Aerolinea Principal Chile S.A.", "5P"),
    ARG("Aerolineas Argentinas", "AR"),
    GLG("Aerolineas Galapagos S.A. Aerogal", "2K"),
    RCQ("Aerolineas Regionales, S.A. de C.V", "F2"),
    ABH("Aerolineas de Baleares AeBal", "DF"),
    SLI("Aerolitoral S.A. de C.V.", "5D"),
    AMX("Aeromexico", "AM"),
    AEW("Aerosvit Airlines", "VV"),
    IBZ("Aerosyncro Aviation AB", "6I"),
    TNO("Aerotransporte de Carga Union, S.A. de C", "6R"),
    MAA("Aerotransportes Mas de Carga", "M7"),
    CBE("Aerovias Caribe S.A. de C.V.", "QA"),
    AVA("Aerovias del Continente Americano S.A", "AV"),
    AIN("African International Airways", ""),
    AAW("Afriqiyah Airways", "8U"),
    AAF("Aigle Azur", "ZI"),
    DAH("Air Algerie", "AH"),
    LMY("Air Almaty JSC", "K7"),
    KZR("Air Astana", "KC"),
    ABD("Air Atlanta Icelandic", "CC"),
    REU("Air Austral", "UU"),
    BBT("Air Bashkortostan Ltd.", "ZU"),
    OBE("Air Bee S.p.A", "BM"),
    BSA("Air Bissau International Lda", "YL"),
    BOT("Air Botswana Corporation", "BP"),
    TPC("Air Caledonie", "TY"),
    ACI("Air Caledonie International", "SB"),
    ACA("Air Canada", "AC"),
    JZA("Air Canada Jazz", "QK"),
    FWI("Air Caraibes", "TX"),
    SNC("Air Cargo Carriers, Inc.", "2Q"),
    ACE("Air Charter Express Limited", ""),
    MPD("Air Comet S.A.", "A7"),
    IKA("Air Company ITEK-AIR Ltd.", "GI"),
    ABR("Air Contractors (UK) Limited", "AG"),
    CRQ("Air Creebec (1994) Inc.", "YN"),
    DLA("Air Dolomiti S.p.A.", "EN"),
    SEE("Air Eagle (Pvt) Ltd.", ""),
    AEA("Air Europa Lineas Aereas, S.A.", "UX"),
    FAJ("Air Fiji Ltd.", "PC"),
    AFR("Air France", "AF"),
    GRL("Air Greenland A/S", "GL"),
    FXI("Air Iceland (Flugfelag Islands)", "NY"),
    AIE("Air Inuit Ltd/Ltee", "3H"),
    AJM("Air Jamaica", "JM"),
    KOR("Air Koryo", "JS"),
    KAV("Air Kurfa", "7F"),
    KIL("Air Lines of Kuban", "GW"),
    ALG("Air Logistics L.L.C. d/b/a", "L9"),
    AMU("Air Macau Company Limited", "NX"),
    MDG("Air Madagascar", "MD"),
    AML("Air Malawi Limited", "QM"),
    AMC("Air Malta p.l.c.", "KM"),
    MRS("Air Marshall Islands, Inc.", "CW"),
    MAU("Air Mauritius", "MK"),
    AMW("Air Midwest", "ZV"),
    MLD("Air Moldova", "9U"),
    NMB("Air Namibia", "SW"),
    NPL("Air Nepal International Pvt. Ltd.", "XN"),
    ANZ("Air New Zealand Limited", "NZ"),
    NXA("Air Next Co., Ltd.", "7A"),
    ANK("Air Nippon Co. Ltd.", "EL"),
    ANG("Air Niugini Pty Limited", "PX"),
    ANE("Air Nostrum L.A.M.S.A.", "YW"),
    ADH("Air One", "AP"),
    FJI("Air Pacific Ltd.", "FJ"),
    GAP("Air Philippines Corporation", "2P"),
    SNG("Air Senegal International", "V7"),
    SEY("Air Seychelles Limited", "HM"),
    ASD("Air Sinai", "4D"),
    SHR("Air Sylhet AG", "SL"),
    VTA("Air Tahiti", "VT"),
    THT("Air Tahiti Nui", "TN"),
    ATC("Air Tanzania Company Ltd.", "TC"),
    TSC("Air Transat", "TS"),
    URG("Air Urga", "3N"),
    AVN("Air Vanuatu (Operations) Limited", "NF"),
    VIM("Air Via Ltd.", "VL"),
    AWI("Air Wisconsin Airlines Corporation", "ZW"),
    AZW("Air Zimbabwe (Pvt) Ltd.", "UM"),
    XAK("AirKenya Express Limited", "P2"),
    BCI("AirX Limited dba Blue Islands", "SI"),
    AXM("Airasia Sdn Bhd.", "AK"),
    ESD("Aircompany Esen Air", "K9"),
    LYN("Aircompany Kyrgyzstan", "QH"),
    AWA("Aircompany Asia Wings JSC", "Y5"),
    AKK("Aklak Inc.", "6L"),
    HJT("Al Rais Cargo Agencies L.L.C.", ""),
    ANH("Alajnihah For Air Transport", "2T"),
    ASC("Alas Del Sur S.R.L", "D4"),
    ASA("Alaska Airlines Inc.", "AS"),
    AER("Alaska Central Express", "KO"),
    LBC("Albanian Airlines MAK S.H.P.K.", "LV"),
    AZA("Alitalia-Compagnia Aerea Italiana S.p.A", "AZ"),
    ANA("All Nippon Airways Co. Ltd.", "NH"),
    LLR("Alliance Air", "CD"),
    AJK("Allied Air Ltd.", "4W"),
    AIP("Alpine Aviation Inc.", "5A"),
    AAL("American Airlines Inc.", "AA"),
    AMF("Ameriflight, LLC", "A8"),
    AJT("Amerijet International Inc.", "M6"),
    AUH("Amiri Flight", "MO"),
    AKW("Angkor Airways Corporation", "G6"),
    CIR("Arctic Circle Air Service Inc.", "5F"),
    AFG("Ariana Afghan Airlines", "FG"),
    AIZ("Arkia - Israeli Airlines Ltd", "IZ"),
    APW("Arrow Air Inc.", "JW"),
    SAL("Asia Alpha Airways", "OD"),
    AAR("Asiana Airlines Inc.", "OZ"),
    DHL("Astar Air Cargo", "ER"),
    AEU("Astraeus Ltd.", "5W"),
    AYZ("Atlant-Soyuz", "7B"),
    FLI("Atlantic Airways Faroe Islands", "RC"),
    ACY("Atlantic Southeast Airlines, Inc.", "EV"),
    KKK("Atlasjet Airlines Inc.", "KK"),
    JOL("Atyrau  Aue Joly", "IP"),
    AUB("Augsburg Airways GmbH & Co. KG", "IQ"),
    AUR("Aurigny Air Services Limited", "GR"),
    XME("Australian Air Express Pty. Ltd.", "XM"),
    AUA("Austrian Airlines, Osterreichische", "OS"),
    PHW("Ave.com", "2E"),
    TUP("Aviastar-TU Co.  Aviacompany", "4B"),
    FRE("Aviation Services, Ltd.", "FP"),
    SMJ("Avient Aviation (PVT) Limited", "Z3"),
    AVC("Avient Cameroon S.A.", "HC"),
    ROI("Aviones de Oriente C.A. (AVIOR)", "9V"),
    AHY("Azerbaijan Hava Yollary", "J2"),
    CFE("BA Cityflyer Limited", "CJ"),
    BHS("Bahamasair Holdings, Limited", "UP"),
    BKP("Bangkok Airways Co. Ltd.", "PG"),
    BKA("Bankair Inc.", "B4"),
    XBO("Baseops International, Inc.", "3Y"),
    BLS("Bearskin Lake air services Ltd.", "JV"),
    BRU("Belavia", "B2"),
    LBY("Belle Air Company", "LZ"),
    BLV("Bellview Airlines Limited", "B3"),
    BMJ("Bemidji Aviation Services, Inc.", "CH"),
    BEA("Best Aviation Ltd.", "5Q"),
    BBC("Biman Bangladesh Airlines", "BG"),
    BPA("Blue Panorama Airlines S.p.A.", "BV"),
    BWG("Blue Wings AG", "QW"),
    BLF("Blue1 Oy", "KF"),
    GWY("Brendan Airways, LLC", "U5"),
    BRC("Bringer Air Cargo Taxi Aereo Ltda", "E6"),
    BZH("Brit Air", "DB"),
    BAW("British Airways p.l.c.", "BA"),
    BMA("British Midland Airways Ltd.", "BD"),
    DAT("Brussels Airlines N.V.", "SN"),
    LZB("Bulgaria Air", "FB"),
    BRQ("Buraq Air Transport (BRQ)", "UZ"),
    VLE("C.A.I. Second S.p.A.", "VE"),
    ICL("C.A.L. Cargo Airlines Ltd.", "5C"),
    CEB("CEBU Pacific Air", "5J"),
    RWZ("CJSC Airline 400", "WZ"),
    VCV("CONVIASA", "V0"),
    CRL("CORSAIR", "SS"),
    CAV("Calm Air International Ltd.", "MO"),
    ANO("Capiteq Limited dba AIRNORTH", "TL"),
    CBB("Cargo B Airlines", "BB"),
    CJT("Cargojet Airways Ltd.", "W8"),
    CLX("Cargolux Airlines International S.A.", "CV"),
    BWA("Caribbean Airlines Limited", "BW"),
    CPN("Caspian Airlines Service Company Ltd.", "RV"),
    CPA("Cathay Pacific Airways Ltd.", "CX"),
    CAY("Cayman Airways Limited", "KX"),
    GLR("Central Mountain Air Ltd.", "9M"),
    CWC("Centurion Air Cargo, Inc.", "WE"),
    CHQ("Chautauqua Airlines Inc.", "RP"),
    CAL("China Airlines", "CI"),
    CES("China Eastern Airlines", "MU"),
    CSN("China Southern Airlines", "CZ"),
    CUA("China United Airlines", "KN"),
    CIU("Cielos del Peru, S.A.", "A2"),
    AUT("Cielos del Sur S.A.", "AU"),
    CIM("Cimber Air A.S.", "QI"),
    SDR("City Airline AB", "CF"),
    BCY("Cityjet", "WX"),
    CGK("Click Airways", "C4"),
    UZS("Closed Joint Stock Company", "C7"),
    CAW("Comair Ltd.", "MN"),
    COM("Comair, Inc.", "OH"),
    CCM("Compagnie Aerienne Corse", "XK"),
    MXA("Compania Mexicana de Aviacion", "MX"),
    CMP("Compania Panamena de Aviacion, S.A.", "CM"),
    VOI("Concesionaria Vuela Compania De Aviacion", "Y4"),
    CFG("Condor Flugdienst GmbH", "DE"),
    KIS("Contact-Air Flugdienst GmbH & Co. KG", "C3"),
    COA("Continental Airlines, Inc.", "CO"),
    CMI("Continental Micronesia, Inc.", "CS"),
    COY("Coyne Airways Ltd", "7C"),
    CTN("Croatia Airlines", "OU"),
    CUB("Cubana de Aviacion S.A.", "CU"),
    CYP("Cyprus Airways Limited", "CY"),
    CSA("Czech Airlines a.s., CSA", "OK"),
    DAE("DHL Aero Expreso S.A.", "D5"),
    DHK("DHL Air Limited", "D0"),
    DHX("DHL International B.S.C. ( c )", "ES"),
    JOS("DHL de Guatemala S.A.", "L3"),
    DAO("Daallo Airlines", "D3"),
    KHB("Dalavia - Far East Airways Khabarovsk", "H8"),
    DAN("Dana Airlines Limited", "9J"),
    DTR("Danish Air Transport", "DX"),
    DWT("Darwin Airline SA Lugano", "0D"),
    DER("Deer Jet Co. Ltd.", "JD"),
    DAL("Delta Air Lines Inc.", "DL"),
    DLH("Deutsche Lufthansa AG", "LH"),
    UDN("Dnieproavia  - Joint Stock Aviation Co.", "Z6"),
    DMO("Domodedovo Airlines", "E3"),
    DRK("Druk Air Corporation Ltd.", "KB"),
    EVA("EVA Airways Corporation", "BR"),
    EDW("Edelweiss Air AG", "WK"),
    MSR("Egyptair", "MS"),
    ELY("El Al Israel Airlines Ltd.", "LY"),
    ESC("El Sol de America", "6S"),
    UAE("Emirates", "EK"),
    MPR("Empire Aviation Limited", ""),
    ERH("Era Aviation, Inc.", "7H"),
    ERT("Eritrean Airlines", "B8"),
    ELL("Estonian Air", "OV"),
    ETH("Ethiopian Airlines Enterprise", "ET"),
    ETD("Etihad Airways", "EY"),
    ECA("Eurocypria Airlines Ltd.", "UI"),
    EEZ("Eurofly S.p.A.", "GJ"),
    MJX("Euroline", "4L"),
    BCS("European Air Transport N.V.", "QY"),
    EWG("Eurowings AG", "EW"),
    EIA("Evergreen International Airlines Inc.", "EZ"),
    EXA("Execaire", "MB"),
    EXV("Expo Aviation (Pvt) Limited", "8D"),
    BTA("ExpressJet Airlines, Inc.", "XE"),
    EZA("Eznis Airways Co. Ltd.", "ZY"),
    QFZ("Fars Qeshm Airlines", "QE"),
    FDX("FedEx", "FX"),
    PLK("Federal State Unitary Enterprise STC", "FV"),
    FXX("Felix Airways", "FO"),
    FIN("Finnair Oyj", "AY"),
    FAB("First Air", "7F"),
    FFV("Five Fourty Aviation Limited", "5H"),
    FWL("Florida West International Airways, Inc.", "RF"),
    FXL("Fly Excellent", "F3"),
    LIL("FlyLAL-Lithuanian Airlines", "TE"),
    BEE("Flybe Limited", "BE"),
    FCR("Flying Carpet Air Transport & Services", "7Y"),
    FSC("Four Star Aviation", "HK"),
    FTA("Frontier Flying Service, Inc.", "2F"),
    FGL("Futura Gael", "F6"),
    GBL("GB Airways Ltd.", "GT"),
    GBK("Gabon Airlines Cargo", "6G"),
    GDR("Gadair European Airlines", "GP"),
    GNR("Gambia International Airlines Ltd.", "GC"),
    GIA("Garuda Indonesia", "GA"),
    GZP("Gazpromavia Aviation Company Ltd.", "4G"),
    GHB("Ghana International Airlines Ltd.", "G0"),
    GSM("Globespan Airways Limited", "Y2"),
    GJS("GoJet Airlines LLC", "G7"),
    GLA("Great Lakes Aviation Ltd.", "ZK"),
    GAI("Gromov Flight Research Institute Airline", "3R"),
    GFA("Gulf Air Company G.S.C.", "GF"),
    GFT("Gulfstream International Airlines, Inc.", "3M"),
    HMY("HMY Airways Inc.", "HQ"),
    HHN("Hahn Air Lines", "HR"),
    CHH("Hainan Airlines Company Limited", "HU"),
    HML("Hamsal Air Services Limited", "2H"),
    HLF("Hapag Lloyd Fluggesellschaft", "HF"),
    HAL("Hawaiian Airlines, Inc.", "HA"),
    MCM("Heli Air Monaco", "YO"),
    JBA("Helijet International Inc.", "JB"),
    HTA("Helitrans AS", "9I"),
    IMP("Hellenic Imperial Airways", "HT"),
    ALX("Hewa Bora Airways", "EO"),
    HWY("Highland Airways Limited", "8H"),
    ADO("Hokkaido Int'l Airlines Co., Ltd.", "HD"),
    HDA("Hong Kong Dragon Airlines Limited", "KA"),
    HKE("Hong Kong Express Airways Limited", "UO"),
    QXE("Horizon Air", "QX"),
    CSQ("IBC Airways, Inc.", "II"),
    IZM("IHY Izmir Havayollari A.S.", "4I"),
    ITX("IMAIR Airline", "IK"),
    IBE("Iberia - Lineas Aereas de Espana", "IB"),
    ICE("Icelandair", "FI"),
    IDO("Indochina Airlines", "IO"),
    INX("Inter Express Hava Tasimacilik A.S.", "6K"),
    ISK("InterSky Luftfahrt GmbH", "3L"),
    ITK("Interlink Airlines (Pty) Ltd.", "ID"),
    FWA("Interstate Airlines B.V.", "I4"),
    IRA("Iran Air", "IR"),
    IRC("Iran Aseman Airlines", "EP"),
    IAW("Iraqi Airways", "IA"),
    ISV("Islena de Inversiones S.A. de C.V.", "WC"),
    ISR("Israir Airlines and Tourism Ltd.", "6H"),
    JAZ("JALways Co. Ltd.", "JO"),
    KAO("JSC KAPO Avia", "G7"),
    LMZ("JSC Starline.kz", "DZ"),
    JAE("Jade Cargo International Company Limited", "JI"),
    JAL("Japan Airlines International Co., Ltd.", "JL"),
    JTA("Japan Transocean Air Co. Ltd.", "NU"),
    JAT("Jat  Airways", "JU"),
    JAI("Jet Airways (India) Limited", "9W"),
    PJS("Jet Aviation Business Jets AG", "PP"),
    EXS("Jet2.com Limited", "LS"),
    JCS("JetClub AG", "0J"),
    JXX("JetX ehf, (Primera Air)", "GX"),
    JSA("Jetstar Asia Airways Pte Ltd", "3K"),
    PIC("Jetstar Pacific Airlines", "BL"),
    JBR("Job Air s.r.o.", "3B"),
    UCR("Joint Stock Company  Air Company", "DW"),
    OMS("Joint Stock Company Omskavia Airlines", "N3"),
    SVL("Joint Stock Company Aircompany Yakutia", "R3"),
    SHU("Joint- Stock Company Sakhalinskie", "HZ"),
    JAV("Jordan Aviation", "R5"),
    JUB("Jubba Airways", "6J"),
    DKH("Juneyao Airlines Co,. Ltd.", "HO"),
    KMI("K-Mile Air Co. Ltd", "8K"),
    KNI("KD Avia Open Joint Stock Company", "KD"),
    KLC("KLM Cityhopper", "WA"),
    KLM("KLM Royal Dutch Airlines", "KL"),
    KFS("Kalitta Charters II, LLC", "CB"),
    KMF("Kam Air", "RQ"),
    KMP("Kampuchea Airlines", "E2"),
    AFJ("Kenosha Aero, Inc. dba Alliance Airlines", "3A"),
    KQA("Kenya Airways", "KQ"),
    LYM("Key Lime Air Corporation", "KG"),
    KYV("Kibris Turk Hava Yollari", "YK"),
    IRK("Kish Airlines", "Y9"),
    KHA("Kitty Hawk Aircargo, Inc.", "KR"),
    KAL("Korean Air Lines Co. Ltd.", "KE"),
    KAC("Kuwait Airways", "KU"),
    KZU("Kuzu Airlines Cargo", "GO"),
    LAB("L.A.B. Flying Service Inc.", "JF"),
    LAM("LAM - Linhas Aereas de Mocambique", "TM"),
    LIA("LIAT (1974) Ltd.", "LI"),
    LOT("LOT - Polish Airlines", "LO"),
    LTE("LTE International Airways S.A.", "XO"),
    LTU("LTU International Airways", "LT"),
    LAL("Labrador Airways Limited", "WJ"),
    LAN("Lan Airlines S.A.", "LA"),
    LCO("Lan Chile Cargo S.A.", "UC"),
    LPE("Lan Peru S.A.", "LP"),
    LAO("Lao Airlines", "QV"),
    LDA("Lauda Air Luftfahrt AG", "NG"),
    LAA("Libyan Airlines", "LN"),
    UDC("Limited Liability Company", "7D"),
    LER("Linea Aerea de Servicio Ejecutivo", "QL"),
    LRC("Lineas Aereas Costarricenses S.A.", "LR"),
    LVG("Livingston S.p.A.", "LM"),
    GEC("Lufthansa Cargo AG", "LH"),
    CLH("Lufthansa CityLine GmbH", "CL"),
    LGL("Luxair", "LG"),
    UKW("Lviv Airlines", "5V"),
    MGL("MIAT - Mongolian Airlines", "OM"),
    MKA("MK Airlines Limited", "7G"),
    SCX("MN Airlines LLC", "SY"),
    MNB("MNG Airlines Cargo", "MB"),
    MAK("Macedonian Airlnes", "IN"),
    IRM("Mahan Airlines", "W5"),
    MAS("Malaysia  Airline System Berhad", "MH"),
    MAH("Malev Hungarian Airlines  Limited", "MA"),
    MDA("Mandarin Airlines Ltd.", "AE"),
    MPH("Martinair Holland N.V.", "MP"),
    MTW("Mauritania Airways", "YD"),
    MXU("Maximus Air Cargo", ""),
    MDM("Mediterranean Aviation Company Ltd.", "N5"),
    ISS("Meridiana S.p.A.", "IG"),
    MNA("Merpati Nusantara Airlines", "MZ"),
    ASH("Mesa Airlines, Inc.", "YV"),
    MES("Mesaba Aviation Inc.", "XJ"),
    MEA("Middle East Airlines AirLiban", "ME"),
    MEP("Midwest Airlines Inc.", "YX"),
    MLR("Mihin Lanka (Pvt) Ltd.", "MJ"),
    MSA("Mistral Air S.r.l.", "7M"),
    MDV("Moldavian Airlines", "2M"),
    MON("Monarch Airlines", "ZB"),
    MGX("Montenegro Airlines", "YM"),
    MTN("Mountain Air Cargo Inc.", "C2"),
    MUA("Murray Air Inc.", "N8"),
    MYT("MyTravel Airways Limited", "VZ"),
    UBA("Myanma Airways", "UB"),
    AIC("NACIL, dba Air India", "AI"),
    IAC("NACIL, dba Indian Airlines", "IC"),
    NOV("NOVA Airlines", "O9"),
    RON("Nauru Air Corporation", "ON"),
    NAY("Naysa", "ZN"),
    NZA("Nayzak Air Transport Company", "M4"),
    AXY("New Axis Airways", "9X"),
    NCA("Nippon Cargo Airlines", "KZ"),
    NDC("Nordic Airlink Holding AB dba flynordic", "LF"),
    NAO("North American Airlines, Inc.", "NA"),
    NWA("Northwest Airlines, Inc.", "NW"),
    PLR("Northwestern Air Lease Ltd.", "J3"),
    NAX("Norwegian Air Shuttle A.S.", "DY"),
    NVR("Nova Airlines AB", "N9"),
    OLT("OLT-Ostfriesische Lufttransport GmbH", "OL"),
    VAS("OOO Atran ", "V8"),
    ONE("Oceanair Linhas Aereas Ltda.", "O6"),
    OAL("Olympic Airlines", "OA"),
    OAS("Oman Air (SAOG)", "WY"),
    OTG("One Two Go Airlines Co. Ltd.", "OG"),
    OHY("Onur Havayollari Tasimacilik A.S.", "8Q"),
    ANU("Operador Aereo Andalus S.A.", "EA"),
    ORB("Orenburg Airlines Federal State", "R2"),
    OLA("Overland Airways Limited", "OJ"),
    PBA("PB Air Company Limited", "9Q"),
    CRG("PT Cardig Air", "8F"),
    IDA("PT. Indonesia Air Transport. Tbk", "I8"),
    AWQ("PT. Indonesia AirAsia", "QZ"),
    MKE("PT. Megantara Air", "9M"),
    PEC("Pacific East Asia Cargo Airlines, Inc.", "Q8"),
    ANV("Pacific Wings, L.L.C.", "LW"),
    PKW("Pak West Airlines Inc.", "P8"),
    PIA("Pakistan International Airlines", "PK"),
    PWD("Pan Am World Airways Dominicana", "7Q"),
    PSC("Pascan Aviation Inc.", "P6"),
    PEN("Penair", "KS"),
    PAL("Philippine Airlines, Inc.", "PR"),
    FLG("Pinnacle Airlines Inc.", "9E"),
    PLS("Platnium Air Linhas Aereas Ltda.", "P2"),
    PMO("Polar Airlines de Mexico S.A. de C.V.", "M4"),
    PGA("Portugalia - Companhia Portuguesa de", "NI"),
    PSK("Prescott Support Company", "PM"),
    PUA("Primeras Lineas Uruguayas de Navegacion", "PU"),
    SPR("Provincial Airlines", "PB"),
    QFA("Qantas Airways Ltd.", "QF"),
    QTR("Qatar Airways(Q.C.S.C)", "QR"),
    RGL("Regional Air Lines", "FN"),
    RMV("Romanian Aviation Company", "WQ"),
    RAM("Royal Air Maroc", "AT"),
    MOD("Royal Airways Limited", "SG"),
    RBA("Royal Brunei Airlines Sdn. Bhd.", "BI"),
    KDR("Royal Daisy Airlines", "6D"),
    RFJ("Royal Falcon", "RZ"),
    RJA("Royal Jordanian", "RJ"),
    RNA("Royal Nepal Airlines Corporation", "RA"),
    RUC("Rutas Aereas, C.A. RUTACA", "RM"),
    RWD("Rwandair Express", "WB"),
    RYN("Ryan International Airlines", "RD"),
    RYR("Ryanair Ltd.", "FR"),
    CNO("SAS Scandinavian Airlines Norge AS", "BU"),
    SAT("SATA - Air Acores", "SP"),
    RZO("SATA International Servicos e", "S4"),
    TUI("SEVENAIR S.A.", "UG"),
    SWQ("SWIFT AIR,L.L.C.", "Q7"),
    SWR("SWISS International Air Lines Ltd", "LX"),
    SFR("Safair (Proprietary) Ltd.", "FA"),
    SFW("Safi Airways Ltd.", "4Q"),
    BRZ("Samara Airlines", "E5"),
    SVA("Saudi Arabian Airlines", "SV"),
    SAH("Sayakhat Airlines", "W7"),
    SAS("Scandinavian Airlines System (SAS)", "SK"),
    EGJ("Scenic Airlines, Inc.", "YR"),
    LRS("Servicios Aereos Nacionales S.A.", "RZ"),
    SAI("Shaheen Air International", "NL"),
    SAW("Sham Wings Airlines", "6Q"),
    CDG("Shandong Airlines", "SC"),
    SHQ("Shanghai Airlines Cargo International", "F4"),
    CSZ("Shenzhen Airlines", "ZH"),
    SBI("Siberia Airlines", "S7"),
    SRH("Siem Reap Airways International", "FT"),
    SLK("SilkAir (S) Pte. Ltd.", "MI"),
    SQC("Singapore Airlines Cargo Pte. Ltd.", "SQ"),
    SIA("Singapore Airlines Limited", "SQ"),
    SHE("Sky Express S.A.", "GQ"),
    SKG("Sky Gabon S.A.", "GV"),
    SJA("Sky Jet Aviation Ltd", "UQ"),
    SKU("Sky Service S.A. dba Sky Airline", "H2"),
    SKZ("Sky Way Enterprises Inc.", "KI"),
    SKT("SkyStar Airways Company Limited", "XT"),
    SKW("SkyWest  Airlines", "OO"),
    SKY("Skymark Airlines Inc.", "BC"),
    SSV("Skyservice Airlines Inc.", "5G"),
    SKX("Skyways AB", "JZ"),
    SAM("Sociedad Aeronautica de Medellin", "MM"),
    OLC("Solar Cargo, C.A.", "4S"),
    SOL("Solomon Airlines", "IE"),
    SAA("South African Airways", "SA"),
    GGG("South-East European Airlines", "G2"),
    SOO("Southern Air Inc.", "9S"),
    SWA("Southwest Airlines Co.", "WN"),
    JKK("Spanair S.A.", "JK"),
    ALK("SriLankan Airlines Limited", "UL"),
    SBO("Stabo Air Limited", ""),
    SRR("Star Air A/S", "S6"),
    SRU("Star Up S.A.", "2I"),
    SLT("Starlight Airline", "QP"),
    SUD("Sudan Airways Co. Ltd.", "SD"),
    SXS("SunExpress", "XQ"),
    SLM("Surinam Airways Ltd.", "PY"),
    SWT("Swiftair", "7J"),
    SYR("Syrian Arab Airlines", "RB"),
    DTA("TAAG - Linhas Aereas de Angola", "DT"),
    TAT("TACA Costa Rica Sociedad Anonima", "TI"),
    LAP("TAM - Transportes Aereos del", "PZ"),
    TAM("TAM Linhas Aereas S.A.", "JJ"),
    TAE("TAME Linea Aerea del Ecuador", "EQ"),
    TAP("TAP - Air Portugal", "TP"),
    ROT("TAROM - Transporturile Aeriene Romane", "RO"),
    TAY("TNT Airways S.A.", "3V"),
    TFL("TUI Airlines Nederland B.V.", "OR"),
    BLX("TUIfly Nordic AB", "6B"),
    TAI("Taca International Airlines, S.A.", "TA"),
    TSD("Taf Linhas Aereas S.A.", "R9"),
    TDM("Tandem Aero Ltd.", "TQ"),
    JPR("Taxi Fly Group S.A.", "P5"),
    VNZ("Tbilaviamsheni", "L6"),
    THA("Thai Airways International Public", "TG"),
    VKG("Thomas Cook Airlines Scandinavia A/S", "DK"),
    TCX("Thomas Cook Airlines U.K. Limited", "MT"),
    TOM("Thomson Airways Limited", "BY"),
    AWC("Titan Airways Limited", "ZT"),
    TDR("Trade Air Ltd.", "8P"),
    TNB("Trans Air Benin", "N4"),
    LOF("Trans States Airlines, Inc.", "AX"),
    TNA("TransAsia Airways Corporation", "GE"),
    TSO("Transaero Airlines", "UN"),
    TRA("Transavia Airlines", "HV"),
    TXC("Transaviaexport Cargo Airline", "AL"),
    TFZ("Transport Africa", "9K"),
    BOL("Transportes Aereos Bolivianos", ""),
    CIE("Transportes Aereos Cielos Andinos S.A.C.", "9P"),
    TPA("Transportes Aereos Mercantiles", "QT"),
    TCV("Transportes Aereos de Cabo Verde", "VR"),
    TAO("Transportes Aeromar, S.A. de C.V.", "VW"),
    TSJ("Trast Aero", "S5"),
    TAR("Tunisair", "TU"),
    URN("Turan Air Airline Company", "3T"),
    THY("Turkish Airlines Inc.", "TK"),
    TUA("Turkmenistan Airlines", "T5"),
    TRK("Turkuaz Airlines", "HK"),
    TYR("Tyrolean Airways Tiroler Luftfahrt GmbH", "VO"),
    UIA("UNI Airways Corporation", "B7"),
    UPS("UPS", "5X"),
    USA("US Airways, Inc.", "US"),
    JUS("USA Jet Airlines, Inc.", "UJ"),
    TMN("UTair Aviation Joint-Stock Company", "UT"),
    AUI("Ukraine International Airlines", "PS"),
    UKM("Ukrainian Mediterranean Airlines Ltd.", "UF"),
    UAL("United Airlines, Inc.", "UA"),
    UVA("Universal Airways, Inc.", "UV"),
    SVR("Ural Airlines", "U6"),
    UZB("Uzbekistan Havo Yullary -", "HY"),
    MOV("VIM Airlines", "NN"),
    VLO("Varig Logistica S/A", "LC"),
    VEC("Vensecar Internacional C.A.", "V4"),
    HVN("Vietnam Airlines Corporation", "VN"),
    VPA("Vip Air, spol. S.r.o", "V5"),
    VRD("Virgin America Inc.", "VX"),
    VIR("Virgin Atlantic Airways Limited", "VS"),
    VOZ("Virgin Blue Airlines Pty Ltd", "DJ"),
    VAU("Virgin Blue International Airlines", "VA"),
    VGN("Virgin Nigeria Airways", "VK"),
    VLK("Vladivostok Air JSC", "XF"),
    VDA("Volga-Dnepr Airline Joint Stock", "VI"),
    VOG("Voyager Airlines Ltd", "V6"),
    WEB("Webjet Linhas Aereas S/A", "WH"),
    WJA("WestJet", "WS"),
    WHT("White Airways S.A.", ""),
    WIF("Wideroe's Flyveselskap A.S.", "WF"),
    WIA("Windward Islands Airways Int'l  N.V.", "WM"),
    WOA("World Airways", "WO"),
    WWI("Worldwide Jet Charter L.L.C.", "T8"),
    XLF("XL Airways France", "SE"),
    CXA("Xiamen Airlines", "MF"),
    LLM("Yamal Airlines", "YC"),
    YZR("Yangtze River Express Airlines Company", "Y8"),
    IYE("Yemenia - Yemen Airways", "IY"),
    ZMA("Zambezi Airlines", "ZJ"),
    MAZ("Zambian Airways", "Q3"),
    OOM("Zoom Airlines Inc.", "Z4"),
    ZAW("Zoom Airways Limited", "3Z"),
    NVD("joint stock company Avion Express", "X9");
    
    private static final Map<String, Carrier> iataMap = new HashMap<>();

    static
    {
        for (Carrier c : values())
        {
            if (c.getIata() != null)
            {
                iataMap.put(c.getIata(), c);
            }
        }
    }
    
    private final String name;
    private final String iata;
    
    private Carrier(String name, String iata) {
        this.name = name;
        this.iata = iata;
    }

    public String getName() {
        return name;
    }

    public String getIata() {
        return iata;
    }
    
    public static Carrier getByIataCode(String iata) {
        return iataMap.get(iata);
    }
}
