package gov.cbp.taspd.gtas.model;

// Generated Jun 15, 2015 7:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Operator generated by hbm2java
 */
@Entity
@Table(name = "operator", catalog = "gtas")
public class Operator implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1969961710671243943L;
	private String opCode;
	private String description;

	public Operator() {
	}

	public Operator(String opCode) {
		this.opCode = opCode;
	}

	public Operator(String opCode, String description) {
		this.opCode = opCode;
		this.description = description;
	}

	@Id
	@Column(name = "OP_CODE", unique = true, nullable = false, length = 16)
	public String getOpCode() {
		return this.opCode;
	}

	public void setOpCode(String opCode) {
		this.opCode = opCode;
	}

	@Column(name = "DESCRIPTION", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
