language: java

sudo: false

jdk:
  - oraclejdk8

notifications:
  slack: gtas:G1lDbK5rR8cNBEhlszZNGDnL
    on_success: change
    on_failure: always

  email:
    recipients:
      - david.j.ertel@cbp.dhs.gov
      - maneesh.lekkala@gmail.com
      -	taylorjwdev@gmail.com
      - jtangfed@gmail.com
      - vempatisvr@gmail.com
      - mikecope@gmail.com

before_script:
  - cd gtas_parent

script: mvn clean verify
